### PR TITLE
Trunk

### PR DESCRIPTION
**Pull request by olear**

### CODE REVIEW

**Comment by devernay** [comment]
@olear I'm linking NatronRendered with a static cairo, would it help if I did the same with Natron itself?

**Comment by olear** [comment]
I'm currently triyng to build pango on CentOS6 against the Natron SDK. Seems the problem is related to old versions of freetype/fontconfig, cairo supplied with Natron may work.

**Comment by olear** [comment]
I need to build libffi, glib, freetype, harfbuzz, freetype, fontconfig, cairo, pango. And all the other depends (qt etc) must be rebuilt against that.... will take some hours to test. Will update natron-linux when done.

**Comment by devernay** [comment]
pango probably doesn't need all that stuff, but it's probably hard to cut things out.
Don't forget to build static versions of these libraries too. That way, you can link to each library one by one and really figure out what's really needed (for example, cairo for Natron only needed freetype, pixman and fontconfig, all other libraries were used by unneeded parts of cairo)

that's the reason why I think plugins should use as little libraries as possible, and that's a major flaw of the plugin architecture.

We should really think about a OpenFX-over-socket protocol, so that OpenFX plugins can be coded as external processes (this would also solve license problems).

fred

**Comment by olear** [comment]
The problem is that I need a new version of Pango to be compatible with Cairo shipped with Natron, but using a "new" version of Pango requires new depends, so glib, freetype, fontconfig must be bumped, and they require additional depends like harfbuzz and libffi etc .....

It's workable, but the only solution on Linux at least. The Pango feature in Text.ofx is not a must-have, but nice for advanced font work.

The plugin architecture is very flawed in this regard.

**Comment by olear** [comment]
Got Pango working in Arena.ofx without modifiy Natron (on Linux).

**Pull request merged**
